# frontend/Dockerfile.frontend

# Sử dụng Node.js làm base image để build React app
FROM node:22-alpine AS build-stage

# Thiết lập thư mục làm việc trong giai đoạn build
WORKDIR /app

# Set up biến môi trường trước khi build
ENV NODE_ENV=production
# # Test trên localhost
# ENV REACT_APP_BACKEND_URL="http://localhost:5000"
# Deploy chính thức
ENV REACT_APP_BACKEND_URL="https://projects.iec-uit.com/MultiViewAR-Detector/api"

# Copy package.json và package-lock.json để cài đặt dependencies
COPY frontend/package*.json ./

# Cài đặt dependencies Node.js
RUN npm install --legacy-peer-deps

# Copy toàn bộ mã nguồn ứng dụng frontend vào container
COPY frontend/ .

# Build ứng dụng cho môi trường production
RUN npm run build

RUN ls -la /app/build

# stage 2: production
FROM nginx:stable-alpine AS production-stage

# Xóa cấu hình mặc định của Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copy cấu hình Nginx tùy chỉnh của bạn
COPY nginx/nginx.conf /etc/nginx/conf.d/

# QUAN TRỌNG: Đảm bảo thư mục 'build' được tạo trong GIAI ĐOẠN BUILD và được copy sang GIAI ĐOẠN PRODUCTION
COPY --from=build-stage /app/build /usr/share/nginx/html/
# Copy thư mục build từ giai đoạn trước

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

